import type { ModeDefinition } from '../types.js';

export const MODE_REGISTRY: ModeDefinition[] = [
  {
    mode_id: 'individual',
    name: 'Individual',
    purpose: 'Single-agent direct execution for straightforward, low-risk tasks',
    trigger_conditions: [
      'low complexity',
      'single-step intent',
      'minimal tool requirements',
      'low risk score',
    ],
    exclusion_conditions: [
      'high workflow depth',
      'parallel decomposition required',
      'elevated safety risk',
    ],
    weight_profile: {
      intent_match: 0.9,
      complexity_match: 0.85,
      safety_match: 0.7,
      workflow_fit: 0.8,
    },
    tool_permissions: ['read', 'write', 'search'],
    confidence_threshold: 0.4,
    fallback_mode: 'individual',
    execution_strategy: 'single_pass',
    output_style: 'concise_direct',
    validation_requirements: ['output_non_empty', 'intent_alignment'],
  },
  {
    mode_id: 'multi_agent',
    name: 'Multi-Agent',
    purpose: 'Parallel specialized workers with merge and synthesis',
    trigger_conditions: [
      'high workflow depth',
      'multiple domains',
      'decomposable task',
      'moderate to high complexity',
    ],
    exclusion_conditions: ['trivial single-step', 'safety block active', 'urgent single answer'],
    weight_profile: {
      intent_match: 0.75,
      complexity_match: 0.95,
      workflow_fit: 0.95,
      tool_match: 0.8,
    },
    tool_permissions: ['read', 'write', 'search', 'delegate', 'merge'],
    confidence_threshold: 0.45,
    fallback_mode: 'individual',
    execution_strategy: 'parallel_workers',
    output_style: 'merged_synthesis',
    validation_requirements: [
      'all_workers_validated',
      'merge_consistency',
      'intent_alignment',
    ],
  },
  {
    mode_id: 'research',
    name: 'Research',
    purpose: 'Iterative information gathering, analysis, and structured findings',
    trigger_conditions: [
      'research intent keywords',
      'explore or compare',
      'documentation output',
      'high ambiguity acceptable',
    ],
    exclusion_conditions: ['pure code generation only', 'safety incident'],
    weight_profile: {
      intent_match: 0.95,
      domain_match: 0.85,
      workflow_fit: 0.9,
      output_fit: 0.9,
    },
    tool_permissions: ['read', 'search', 'fetch', 'summarize'],
    confidence_threshold: 0.42,
    fallback_mode: 'individual',
    execution_strategy: 'iterative_research',
    output_style: 'structured_report',
    validation_requirements: ['sources_cited', 'findings_complete'],
  },
  {
    mode_id: 'build',
    name: 'Build',
    purpose: 'Implementation-focused pipeline with artifacts and verification',
    trigger_conditions: [
      'implement or create',
      'code or scaffold',
      'build artifacts expected',
    ],
    exclusion_conditions: ['read-only review only', 'blocked unsafe actions'],
    weight_profile: {
      intent_match: 0.9,
      complexity_match: 0.85,
      tool_match: 0.95,
      output_fit: 0.85,
    },
    tool_permissions: ['read', 'write', 'execute', 'test'],
    confidence_threshold: 0.43,
    fallback_mode: 'individual',
    execution_strategy: 'build_pipeline',
    output_style: 'code_and_summary',
    validation_requirements: ['build_success', 'tests_optional', 'intent_alignment'],
  },
  {
    mode_id: 'review',
    name: 'Review',
    purpose: 'Quality, security, and correctness review without primary authoring',
    trigger_conditions: [
      'review or audit',
      'PR feedback',
      'quality gate',
    ],
    exclusion_conditions: ['greenfield implementation primary'],
    weight_profile: {
      intent_match: 0.95,
      safety_match: 0.85,
      output_fit: 0.9,
    },
    tool_permissions: ['read', 'diff', 'lint', 'comment'],
    confidence_threshold: 0.41,
    fallback_mode: 'individual',
    execution_strategy: 'review_loop',
    output_style: 'findings_list',
    validation_requirements: ['issues_categorized', 'severity_assigned'],
  },
  {
    mode_id: 'debug',
    name: 'Debug',
    purpose: 'Root-cause analysis, reproduction, and fix verification',
    trigger_conditions: [
      'error or bug',
      'failing tests',
      'stack trace present',
    ],
    exclusion_conditions: ['no failure signals', 'creative brainstorming only'],
    weight_profile: {
      intent_match: 0.95,
      complexity_match: 0.8,
      safety_match: 0.75,
    },
    tool_permissions: ['read', 'write', 'execute', 'trace', 'log'],
    confidence_threshold: 0.44,
    fallback_mode: 'safety',
    execution_strategy: 'debug_trace',
    output_style: 'root_cause_report',
    validation_requirements: ['repro_documented', 'fix_verified'],
  },
  {
    mode_id: 'creative',
    name: 'Creative',
    purpose: 'Exploratory ideation, alternatives, and non-deterministic brainstorming',
    trigger_conditions: [
      'brainstorm or design',
      'multiple alternatives',
      'low risk creative output',
    ],
    exclusion_conditions: ['production deploy', 'high safety risk', 'strict compliance'],
    weight_profile: {
      intent_match: 0.85,
      output_fit: 0.95,
      ambiguity: 0.9,
    },
    tool_permissions: ['read', 'generate', 'branch'],
    confidence_threshold: 0.38,
    fallback_mode: 'individual',
    execution_strategy: 'creative_branch',
    output_style: 'alternatives_rich',
    validation_requirements: ['alternatives_count', 'intent_alignment'],
  },
  {
    mode_id: 'safety',
    name: 'Safety',
    purpose: 'Risk containment, policy enforcement, and safe fallback execution',
    trigger_conditions: [
      'high risk score',
      'unsafe action detected',
      'policy violation keywords',
    ],
    exclusion_conditions: ['explicit low-risk override with audit'],
    weight_profile: {
      safety_match: 1.0,
      risk: 1.0,
      intent_match: 0.6,
    },
    tool_permissions: ['read', 'audit', 'block'],
    confidence_threshold: 0.5,
    fallback_mode: 'individual',
    execution_strategy: 'safety_gate',
    output_style: 'policy_notice',
    validation_requirements: ['risk_acknowledged', 'escalation_blocked'],
  },
];

export function getModeById(modeId: string): ModeDefinition | undefined {
  return MODE_REGISTRY.find((m) => m.mode_id === modeId);
}

export function getAllModeIds(): ModeDefinition['mode_id'][] {
  return MODE_REGISTRY.map((m) => m.mode_id);
}
